version: "3.8"

services:
  app:
    container_name: app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    image: postgres:alpine3.16
